"""Add audit log table

Revision ID: 19a2e925c36e
Revises: 7bd513569a82
Create Date: 2025-09-24 11:19:11.753482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a2e925c36e'
down_revision = '7bd513569a82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_records',
    sa.Column('original_table', sa.String(length=128), nullable=False),
    sa.Column('original_pk', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('archived_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_records_archived_at'), 'archived_records', ['archived_at'], unique=False)
    op.create_index(op.f('ix_archived_records_original_table'), 'archived_records', ['original_table'], unique=False)
    op.create_table('devkit_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_pk', sa.Text(), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_log_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devkit_audit_log_action'), 'devkit_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_devkit_audit_log_record_pk'), 'devkit_audit_log', ['record_pk'], unique=False)
    op.create_index(op.f('ix_devkit_audit_log_table_name'), 'devkit_audit_log', ['table_name'], unique=False)
    op.create_index(op.f('ix_devkit_audit_log_timestamp'), 'devkit_audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_devkit_audit_log_user_id'), 'devkit_audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devkit_audit_log_user_id'), table_name='devkit_audit_log')
    op.drop_index(op.f('ix_devkit_audit_log_timestamp'), table_name='devkit_audit_log')
    op.drop_index(op.f('ix_devkit_audit_log_table_name'), table_name='devkit_audit_log')
    op.drop_index(op.f('ix_devkit_audit_log_record_pk'), table_name='devkit_audit_log')
    op.drop_index(op.f('ix_devkit_audit_log_action'), table_name='devkit_audit_log')
    op.drop_table('devkit_audit_log')
    op.drop_index(op.f('ix_archived_records_original_table'), table_name='archived_records')
    op.drop_index(op.f('ix_archived_records_archived_at'), table_name='archived_records')
    op.drop_table('archived_records')
    # ### end Alembic commands ###
